/*
Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa

*/
#include <bits/stdc++.h>
#define en "\n"
using namespace std;
string str;
set<string> allSub(string &str, int index, string curr, set<string> &all)
{
    if (index == str.length())
    {
        all.insert(curr);
        return all;
    }
    allSub(str, index + 1, curr, all);
    allSub(str, index + 1, curr + str[index], all);
    return all;
}
int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    cin >> str;
    set<string> all;
    allSub(str, 0, "", all);
    for (auto val : all)
    {
        cout << val << " ";
    }
    cout << en;
    return 0;
}